LogiticsWebApp/Areas/Vendor/Models/DriverViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LogiticsWebApp.Areas.Vendor.Models
{
    public class DriverViewModel
    {
        public string Id { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

}

LogiticsWebApp/Areas/Driver/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LogiticsWebApp.Areas.Driver.Controllers
{
    [Area("Driver")]
    [Authorize(Roles = "Driver")]
    public class BaseController : Controller
    {
       
    }
}

LogiticsWebApp/Areas/Driver/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LogiticsWebApp.Areas.Driver.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LogiticsWebApp/Areas/Vendor/Controllers/DriversController.cs
using LogiticsWebApp.Areas.Vendor.Models;
using LogiticsWebApp.Data;
using LogiticsWebApp.Repositories;
using LogiticsWebApp.Utilities;
using LogiticsWebApp.Utilities.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace LogiticsWebApp.Areas.Vendor.Controllers
{
    public class DriversController : BaseController
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserRepository _userRepository;
        private readonly INotificationService _notifictionService;
        private readonly VendorsDriverMapRepository _vendorDriverMapRepository;
        private readonly LogisticDbContext _db;
        public DriversController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IUserRepository userRepository,
            INotificationService notificationService,
            VendorsDriverMapRepository vendorsDriverRepository,
            LogisticDbContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _userRepository = userRepository;
            _notifictionService = notificationService;
            _vendorDriverMapRepository = vendorsDriverRepository;
            _db = db;
        }

        public IActionResult Index() => RedirectToAction(nameof(List));

        [HttpGet]
        public IActionResult List()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetDriversListAsync(int currentPageIndex,
            string search = "",
            int rows = 10)
        {
            var user = await _userManager.FindByEmailAsync(User.Identity.Name);
            return PartialView("_DriversListView", _userRepository.GetDrivers(user.Id, currentPageIndex, search, rows));
        }

        [HttpGet]
        public IActionResult Create()
        {
            DriverViewModel driverViewModel = new DriverViewModel();
            return View(driverViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DriverViewModel driverViewModel)
        {
            if (ModelState.IsValid)
            {
                var driver = await _userManager.FindByEmailAsync(driverViewModel.Email);
                if (driver != null)
                {
                    ModelState.AddModelError(string.Empty, "Email already taken. Please try with another email.");
                    return View(driverViewModel);
                }
                var user = new ApplicationUser
                {
                    UserName = driverViewModel.Email,
                    Email = driverViewModel.Email,
                    EmailConfirmed = true,
                    FirstName = driverViewModel.FirstName,
                    LastName = driverViewModel.LastName,
                    PhoneNumber = driverViewModel.PhoneNumber,
                    Phone = driverViewModel.PhoneNumber
                };
                var result = await _userManager.CreateAsync(user, driverViewModel.Password);
                await _userManager.AddToRoleAsync(user, UserRoles.Driver.ToString());
                var vendor = await _userManager.FindByEmailAsync(User.Identity.Name);
                _userRepository.MapDriverToVendor(user.Id, vendor.Id);

                if (result.Succeeded)
                {
                    _notifictionService.SuccessNotification(CommonConstants.ItemAddedSuccessfully);
                    return RedirectToAction(nameof(List));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(driverViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            var driverViewModel = new DriverViewModel()
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                PhoneNumber = user.Phone,
                Email = user.Email,
                Password = user.PasswordHash
            };
            return View(driverViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DriverViewModel driverViewModel)
        {
            ModelState.Remove(nameof(driverViewModel.Password));
            ModelState.Remove(nameof(driverViewModel.Email));
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(driverViewModel.Id);
                user.Phone = driverViewModel.PhoneNumber;
                user.PhoneNumber = driverViewModel.PhoneNumber;
                user.FirstName = driverViewModel.FirstName;
                user.LastName = driverViewModel.LastName;
                await _userManager.UpdateAsync(user);
                _notifictionService.SuccessNotification(CommonConstants.ItemUpdatedSuccessfully);
                return RedirectToAction(nameof(List));
            }
            return View(driverViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            var driverViewModel = new DriverViewModel()
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                PhoneNumber = user.Phone,
                Email = user.Email,
                Password = user.PasswordHash,
                Id = id
            };
            return View(driverViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var vendor = await _userManager.FindByEmailAsync(User.Identity.Name);
            var vendorDriverMap = _vendorDriverMapRepository.GetVendorDriverMap(vendor.Id, id);
            _vendorDriverMapRepository.Delete(vendorDriverMap.Id);
            var user = await _userManager.FindByIdAsync(id);
            var result = await _userManager.DeleteAsync(user);

            if (result.Succeeded)
            {
                return Json(new
                {
                    Message = CommonConstants.ItemDeletedSuccessfully,
                    Status = NotificationStatus.Success.ToString()
                });
            }
            else
            {
                var errors = string.Empty;
                foreach (var error in result.Errors)
                {
                    errors += error.Description + @", ";
                }
                errors = errors.TrimEnd(',');
                return Json(new
                {
                    Message = errors,
                    Status = NotificationStatus.Errors.ToString()
                });
            }
        }

        [HttpGet]
        public IActionResult ChangePassword(string username)
        {
            ResetPasswordModel resetPasswordModel = new ResetPasswordModel();
            resetPasswordModel.Email = username;
            return View(resetPasswordModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ResetPasswordModel resetPasswordModel)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(resetPasswordModel.Email);
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);

                var result = await _userManager.ResetPasswordAsync(user, code, resetPasswordModel.Password);

                if (result.Succeeded)
                {
                    _notifictionService.SuccessNotification(CommonConstants.PasswordUpdatedSuccessfully);
                    return RedirectToAction(nameof(List));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(resetPasswordModel);
        }



    }
}

LogiticsWebApp/Areas/Vendor/Views/Drivers/ChangePassword.cshtml
@model LogiticsWebApp.Areas.Vendor.Models.ResetPasswordModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
    <br />
    <div class="row">
        <div class="col-md-6 ">

            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Change Password</h3>
                </div>
                <div class="card-body">

                    <form asp-action="ChangePassword" method="post">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Email" name="Email" data-val="true" data-val-required="The user email is required" value="@Model.Email" />
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input asp-for="Password" type="password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ConfirmPassword" class="control-label"></label>
                            <input asp-for="ConfirmPassword" type="password" class="form-control" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>

                        <div class="form-group text-right">
                            <a asp-action="Index" value="Cancel" class="btn btn-danger">Cancel</a>
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>



</div>

LogiticsWebApp/Areas/Vendor/Views/Drivers/Create.cshtml
@model LogiticsWebApp.Areas.Vendor.Models.DriverViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
    <br />
    <div class="row">
        <div class="col-md-6 ">
           
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Register Driver</h3>
                </div>
                <div class="card-body">

                    <form asp-action="Create" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>


                        <div class="form-group text-right">
                            <a asp-action="Index" value="Cancel" class="btn btn-danger">Cancel</a>
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>



        </div>
    </div>



</div>

LogiticsWebApp/Areas/Vendor/Views/Drivers/Detail.cshtml
@model LogiticsWebApp.Areas.Vendor.Models.DriverViewModel

@{
    ViewData["Title"] = "Detail";
}
<div class="container-fluid">
    <br />
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Detail</h3>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.FirstName)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.FirstName)
                        </dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.LastName)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.LastName)
                        </dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.PhoneNumber)
                        </dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.Email)
                        </dd>
                    </dl>
                </div>

                <div class="form-group text-right p-4">
                    <a asp-action="Index" class="btn btn-default">Back to List</a>
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>

                </div>
            </div>
        </div>
    </div>

</div>

LogiticsWebApp/Areas/Vendor/Views/Drivers/Edit.cshtml
@model LogiticsWebApp.Areas.Vendor.Models.DriverViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
    <br />
    <div class="row">
        <div class="col-md-6 ">

            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Update Driver</h3>
                </div>
                <div class="card-body">

                    <form asp-action="Edit" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" disabled/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>


                        <div class="form-group text-right">
                            <a asp-action="Index" value="Cancel" class="btn btn-danger">Cancel</a>
                            <input type="submit" value="Update" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>



        </div>
    </div>



</div>

LogiticsWebApp/Areas/Vendor/Views/Drivers/List.cshtml
@{
    ViewData["Title"] = "List";
}

@using LogiticsWebApp.Utilities.Enums
<br />

<div class="container-fluid">
    <div class="row">
        <div class="col-12 p-2">
            <div class="text-right">
                <a asp-action="Create" asp-controller="Drivers" asp-area="Vendor" class="btn btn-primary">Create New</a>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Driver List</h3>
                    <div class="card-tools">
                        <div class="input-group input-group-sm">
                            <input type="text" name="table_search" id="search-field" class="form-control float-right" placeholder="Search">

                            <div class="input-group-append">
                                <button type="button" onclick="getSearchInput();" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div id="driver-list">
                    </div>
                </div>


            </div>
        </div>
    </div>

    @section Scripts{
        <script>

            $(function () {
                pagerClick();
            });

            function getSearchInput() {
                var searchInput = $("#search-field").val();
                pagerClick(1,searchInput);
            }
            function rowsOnchange() {
                pagerClick(null,null,$("#ddlRows").val());
            }
            function pagerClick(index, search, rows) {
                index = index || 1;
                search = search || '';
                rows = rows || 10;

                var url = "/Vendor/Drivers/GetDriversList";
                url = url + "?currentPageIndex=" + index + "";
                url = url + "&search=" + search + "";
                url = url + "&rows=" + rows + "";
                loadDiv(url, "driver-list");
            }
            var driverId = "";
            function setDriverId(id) {
                driverId = id;
            }
            function deleteDriver_Error(result) {
                showError(result.statusText);
            }
            function deleteDriver_Success(result) {
                hideDialog('modal-default');
                if (result.status === "@NotificationStatus.Success.ToString()") {
                    showSuccess(result.message);
                    pagerClick(1);
                } else{
                    showWarning(result.message);
                }
            }
            function deleteDriver() {
                var params = $.extend({}, doAjax_params_default);
                params['url'] = "/Vendor/Drivers/Delete";
                params['data'] = { id: driverId };
                params['successCallbackFunction'] = deleteDriver_Success;
                params['errorCallBackFunction'] = deleteDriver_Error;
                params['requestType'] = "Post";
                doAjax(params);
            }
        </script>
    }

</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Confirmation</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this driver?</p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="deleteDriver()">Ok</button>
            </div>
        </div>
    </div>
</div>

LogiticsWebApp/Areas/Vendor/Views/Drivers/_DriversListView.cshtml
@{
    Layout = null;
}
@model GridModel<DriverViewModel>

<table cellpadding="0" cellspacing="0" class="table table-head-fixed table-bordered table-striped">
    <thead>
        <tr class="">
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.List)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td class=" ">
                    <a class="btn btn-default btn-xs" asp-action="ChangePassword" asp-route-username="@item.Email">
                        <i class="fas fa-user-secret">
                        </i>
                        Change Password
                    </a>
                    <a class="btn btn-primary btn-xs" asp-action="Detail" asp-route-id="@item.Id">
                        <i class="fas fa-folder">
                        </i>
                        View
                    </a>
                    <a class="btn btn-info btn-xs" asp-action="Edit" asp-route-id="@item.Id">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>

                    <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#modal-default" onclick="setDriverId('@item.Id')">
                        <i class="fas fa-trash">
                        </i>
                        Delete
                    </button>

                </td>

            </tr>
        }
    </tbody>

</table>

<div class="card-footer clearfix">
    <div class="row">
        <div class="col-6">
            <ul class="pagination pagination-sm m-0 float-left">

                <li class="page-item"><a class="page-link" href="#"><i class="fa fa-arrow-left"></i></a></li>
                @for (int i = 1; i <= Model.PageCount; i++)
                {

                    @if (i != Model.CurrentPageIndex)
                    {
                        <li class="page-item">
                            <button class="page-link" onclick="pagerClick(@i);">@i</button>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <button class="page-link" onclick="pagerClick(@i);">@i</button>
                        </li>
                    }

                }
                <li class="page-item"><a class="page-link" href="#"><i class="fa fa-arrow-right"></i></a></li>
            </ul>
        </div>
        <div class="col-4">
            <div class="text-center">
                <div class="dataTables_length">

                    <div class="row">
                        <label class="label" style="margin-top: 6px;padding-right: 6px;">Show</label>

                        <select name="orders-grid_length" aria-controls="orders-grid" id="ddlRows" onchange="rowsOnchange();" class="form-control input-sm col-3">
                            @foreach (var r in Model.AvailableRows)
                            {
                                if (r.Value == Model.SelectedRow)
                                {
                                    <option value="@r.Value" selected>@r.Text</option>
                                }
                                else
                                {
                                    <option value="@r.Value">@r.Text</option>
                                }

                            }
                        </select>
                        <label class="label" style="margin-top: 6px;padding-left: 6px;">Items</label>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            <span><label style="margin-top: 6px;padding-right: 6px;">Total Count : </label>@Model.TotalCount</span>
            <button class="btn btn-default float-right" onclick="pagerClick();" type="button"><i class="fa fa-recycle"></i></button>
        </div>
    </div>

</div>