LogiticsWebApp/ViewComponents/NotificationViewComponent.cs
using LogiticsWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace LogiticsWebApp.ViewComponents
{
    public class NotificationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Run(() =>
            {
                if (TempData.ContainsKey("Notifications"))
                {
                    var notifyData = JsonConvert.DeserializeObject<NotifyDataModel>(TempData["Notifications"].ToString());

                    return View("~/Views/Components/Notification/Default.cshtml", notifyData);
                }
                return View();
            });
        }
    }
}

LogiticsWebApp/Views/Shared/_DriverSideMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using LogiticsWebApp.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        @*<div class="image">
                <img src="~/images/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>*@
        <div class="info">
            <a href="#" class="d-block">Hello @User.Identity.Name!</a>
        </div>
    </div>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
         
            <li class="nav-item">
                <a href="@Url.Action("List", "Drivers", new { area="Vendor"})" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Manage Drivers
                    </p>
                </a>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("List", "Order", new { area="Vendor" })" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Orders
                    </p>
                </a>
            </li>
        </ul>
    </nav>


    <!-- /.sidebar-menu -->
</div>

LogiticsWebApp/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 1.0
    </div>
    @*<strong>Copyright &copy; 2020-2021 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>*@ All rights
    reserved.
</footer>

LogiticsWebApp/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@using LogiticsWebApp.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Home/Index" class="nav-link">Home</a>
        </li>

    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        @if (SignInManager.IsSignedIn(User))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
            </li>
            <li class="nav-item">
                <form class="form-inline" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </li>
        }
        else
        {

            <li class="nav-item">
                <a class="nav-link text-dark" asp-page="/Account/Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-page="/Account/Login">Login</a>
            </li>

        }

    </ul>
</nav>

LogiticsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogiticsWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Logitics Web App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @*<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LogiticsWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LogiticsWebApp/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Logistic Web App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="~/css/adminlte.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="~/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/css/custom-datatable.css" rel="stylesheet" />
</head>
<body class="hold-transition sidebar-mini layout-navbar-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <partial name="_Header" />
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="/" class="brand-link elevation-4">
                <span class="brand-text font-weight-light">Logistic Web App</span>
            </a>
            <partial name="_VendorSideMenu" />
        </aside>
        <div class="content-wrapper">
            <main role="main" class="middleWrapper">
                <div class="padding-section">
                    @if (TempData.ContainsKey("Notifications"))
                    {
                        <div id="NavStatusMsg">
                            @await Component.InvokeAsync("Notification")
                        </div>
                    }
                    @RenderBody()
                </div>
            </main>
        </div>
        <partial name="_Footer" />
    </div>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.dataTables.js"></script>
    <script src="~/js/dataTables.bootstrap.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/additional-methods.min.js"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/fontawesome.min.js"></script>
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/js/demo.js"></script>
    <script src="~/js/common-utility.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LogiticsWebApp/Views/Shared/_LayoutApp.cshtml
@*@using Microsoft.AspNetCore.Identity
@using LogiticsWebApp.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject RoleManager<ApplicationUser> RoleManager
@using LogiticsWebApp.Utilities.Enums

@{
    var user = await UserManager.FindByEmailAsync(User.Identity.Name);
    var roles = await UserManager.GetRolesAsync(user);
    var userrole = roles.FirstOrDefault();
}*@
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/apps/vendor/bootstrap/css/bootstrap.min.css">
    <link href="~/apps/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/apps/libs/css/style.css">
    <link rel="stylesheet" href="~/apps/vendor/fonts/fontawesome/css/fontawesome-all.css">
    <link rel="stylesheet" href="~/apps/vendor/charts/chartist-bundle/chartist.css">
    <link rel="stylesheet" href="~/apps/vendor/charts/morris-bundle/morris.css">
    <link rel="stylesheet" href="~/apps/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/apps/vendor/charts/c3charts/c3.css">
    <link rel="stylesheet" href="~/apps/vendor/fonts/flag-icon-css/flag-icon.min.css">
    <title>Concept - Bootstrap 4 Admin Dashboard Template</title>
</head>

<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
        <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
        <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">
                @*@{
                    var title = userrole == UserRoles.Driver.ToString()
                        ? "Driver" : "Customer";
                }*@
                <a class="navbar-brand" href="index.html">Logistics</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-right-top">
                        <li class="nav-item">
                            <div id="custom-search" class="top-search-bar">
                                <input class="form-control" type="text" placeholder="Search..">
                            </div>
                        </li>
                   
                       
                        <li class="nav-item dropdown nav-user">
                            <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/apps/images/avatar-1.jpg" alt="" class="user-avatar-md rounded-circle"></a>
                            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                                <div class="nav-user-info">
                                    <h5 class="mb-0 text-white nav-user-name">John Abraham </h5>
                                    <span class="status"></span><span class="ml-2">Available</span>
                                </div>
                                <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>Account</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-cog mr-2"></i>Setting</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-power-off mr-2"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
        <div class="nav-left-sidebar sidebar-dark">
            <div class="menu-list">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-divider">
                                Menu
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="">Dashboard</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end left sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- wrapper  -->
        <!-- ============================================================== -->
        <div class="dashboard-wrapper">
            <div class="dashboard-ecommerce">
                <div class="container-fluid dashboard-content ">
                    @RenderBody()


                </div>
            </div>
            <div class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            Copyright © 2018 Concept. All rights reserved. Dashboard by <a href="https://colorlib.com/wp/">Colorlib</a>.
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="text-md-right footer-links d-none d-sm-block">
                                <a href="javascript: void(0);">About</a>
                                <a href="javascript: void(0);">Support</a>
                                <a href="javascript: void(0);">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>

        <!-- ============================================================== -->
        <!-- end wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- end main wrapper  -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->
    <!-- jquery 3.3.1 -->
    <script src="~/apps/vendor/jquery/jquery-3.3.1.min.js"></script>
    <!-- bootstap bundle js -->
    <script src="~/apps/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="~/apps/vendor/slimscroll/jquery.slimscroll.js"></script>
    <!-- main js -->
    <script src="~/apps//libs/js/main-js.js"></script>
    <!-- chart chartist js -->
    <script src="~/apps/vendor/charts/chartist-bundle/chartist.min.js"></script>
    <!-- sparkline js -->
    <script src="~/apps/vendor/charts/sparkline/jquery.sparkline.js"></script>
    <!-- morris js -->
    <script src="~/apps/vendor/charts/morris-bundle/raphael.min.js"></script>
    <script src="~/apps/vendor/charts/morris-bundle/morris.js"></script>
    <!-- chart c3 js -->
    <script src="~/apps/vendor/charts/c3charts/c3.min.js"></script>
    <script src="~/apps/vendor/charts/c3charts/d3-5.4.0.min.js"></script>
    <script src="~/apps/vendor/charts/c3charts/C3chartjs.js"></script>
    <script src="~/apps//libs/js/dashboard-ecommerce.js"></script>
</body>

</html>

LogiticsWebApp/Views/Shared/_VendorSideMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using LogiticsWebApp.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        @*<div class="image">
                <img src="~/images/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>*@
        <div class="info">
            <a href="#" class="d-block">Hello @User.Identity.Name!</a>
        </div>
    </div>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
         
            <li class="nav-item">
                <a href="@Url.Action("List", "Drivers", new { area="Vendor"})" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Manage Drivers
                    </p>
                </a>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("List", "Order", new { area="Vendor" })" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Orders
                    </p>
                </a>
            </li>
        </ul>
    </nav>


    <!-- /.sidebar-menu -->
</div>